### ISSUE TITLE
key读不出来

### ISSUE THREAD

**Issue by Dreamer0510** [tzfun/etcd-workbench#2]
使用docker部署   连接正常  用户获取正常  但是数据读不到
![image](https://github.com/tzfun/etcd-workbench/assets/45943347/338db226-2f53-4183-8eb8-04ecfc221543)
![image](https://github.com/tzfun/etcd-workbench/assets/45943347/38477cb8-e926-4ded-8579-648da93276f4)
![image](https://github.com/tzfun/etcd-workbench/assets/45943347/a58b355b-15b7-437d-b45f-bc6b9c36a868)
![image](https://github.com/tzfun/etcd-workbench/assets/45943347/a733f05c-6b2f-4acc-bc56-323faad6cc0b)

**Comment by Dreamer0510** [comment]
![image](https://github.com/tzfun/etcd-workbench/assets/45943347/974ef90c-3fa7-465a-bd39-c1507558c875)

**Comment by tzfun** [comment]
看一下你的连接信息呢，连接时如果填了 Namespace 是会自动过滤掉该前缀

**Comment by tzfun** [comment]
如果想不过滤任何前缀，显示全部keys，可以不填namespace

**Comment by tzfun** [comment]
应该是你docker相关配置的问题，请求的端口不一致了，你用host模式启动试一下呢

另外确认一下镜像版本是否是 1.1.1

**Comment by Dreamer0510** [comment]
用不了

**Comment by tzfun** [comment]
提供一下你的etcd版本，我这边尝试复现一下。

有一些开发者在docker环境中运行是正常的，包括我平时的生产环境，目前只有你出现了这个情况，方便的话可以加我微信沟通：beifeng-tz
