### ISSUE TITLE
Save to Favorites时报错

### ISSUE THREAD

**Issue by yongjun925** [tzfun/etcd-workbench#21]
<img width="848" alt="image" src="https://github.com/tzfun/etcd-workbench/assets/13444070/2f934e0a-1bd7-4f0c-93cd-25a15e2b6b96">

**Comment by tzfun** [comment]
你用的是什么版本？我在demo中没有复现:
[etcd.beifengtz.com](etcd.beifengtz.com)
- test
- test

**Comment by yongjun925** [comment]
我知道原因了，是之前配置的configEncryptKey 不是16 characters

**Comment by tzfun** [comment]
> 我知道原因了，是之前配置的configEncryptKey 不是16 characters

好的，后面我对这个配置加一下校验，优化一下提示
