### ISSUE TITLE
无法记录文件的 Format格式

### ISSUE THREAD

**Issue by yongjun925** [tzfun/etcd-workbench#22]
每次都需要重新选择文件的 Format格式，是否能在前端页面中记录选择的 Format格式

**Comment by tzfun** [comment]
对部分格式有自动识别的，你的格式是什么类型？可否发一下存储的key和value示例，或许识别规则漏掉了你的这种case

**Comment by yongjun925** [comment]
我明白了，这个文件类型识别是按文件后缀识别的，我这个yaml文件并没有文件后缀

**Comment by yongjun925** [comment]
还有是否可以增加graphql文件类型的支持，感谢

**Comment by tzfun** [comment]
> 我明白了，这个文件类型识别是按文件后缀识别的，我这个yaml文件并没有文件后缀

文件类型识别优先识别后缀，如果识别不到只有特定的文件才会识别内容，比如json

**Comment by tzfun** [comment]
> 还有是否可以增加graphql文件类型的支持，感谢

graphql 文件格式的高亮不一定可以，我需要去寻找一下依赖编辑插件的支持的语言有没有它，我是用了 `vue-codemirror` ，如果你找到了对应语言的高亮样式可以提供在这个issue
