### ISSUE TITLE
建议加个收藏功能，可以把用户常用的节点路径收藏，避免太多配置寻找不方便

### ISSUE THREAD

**Issue by zhoukai83** [tzfun/etcd-workbench#28]
建议加个收藏功能，可以把用户常用的节点路径收藏，避免太多配置节点寻找不方便

**Comment by tzfun** [comment]
你是指在一个session连接内可以收藏key吗？

**Comment by zhoukai83** [comment]
> 你是指在一个session连接内可以收藏key吗？

我想能全局收藏key, 这样不管什么时候，都只关注我重点想看的键值就好了。在大团队里，大家共用一个etcd,, 有成百上千的配置，一般我只需要关注其中少数几个

**Comment by tzfun** [comment]
> 我想能全局收藏key, 这样不管什么时候，都只关注我重点想看的键值就好了。在大团队里，大家共用一个etcd,, 有成百上千的配置，一般我只需要关注其中少数几个

收藏key的功能建议不错，可以支持下，但我更建议是放在每个连接下保存，同一个etcd不太可能会同时打开多个连接，应对多连接场景其他节点收藏的key多了之后可能会干扰用户选择。

**Comment by hoysoft** [comment]
> > 我想能全局收藏key, 这样不管什么时候，都只关注我重点想看的键值就好了。在大团队里，大家共用一个etcd,, 有成百上千的配置，一般我只需要关注其中少数几个
> 
> 收藏key的功能建议不错，可以支持下，但我更建议是放在每个连接下保存，同一个etcd不太可能会同时打开多个连接，应对多连接场景其他节点收藏的key多了之后可能会干扰用户选择。

如果对收藏的部分key（如严重错误标志），能设置 是否进行监控， 就更方便了。当需要监控的值发生改变，弹出提示消息
