### ISSUE TITLE
集群有3w+的KEY，如何优化访问性能

### ISSUE THREAD

**Issue by vnline** [tzfun/etcd-workbench#30]
如题，在加载key时，会出现加载很慢或者查询KEY会出现页面卡死的问题，要如何优化数据加载？

**Comment by tzfun** [comment]
这3W个key都是在同一个路径下的吗？

- 如果不是，那你可以在连接时指定 namespace （相当于指定前缀），这样可以只获取部分路径下的key减少拉取数据量
- 如果是，目前版本没有更好的处理办法，我会尝试在后面版本优化这个问题，看看分页加载可不可行

**Comment by vnline** [comment]
好的，谢谢。在使用鉴权模式时，分配特定前辍路径权限，使用账号密码去连接测试时会报连接超时的问题，命令行是正常的。

**Comment by tzfun** [comment]
> 好的，谢谢。在使用鉴权模式时，分配特定前辍路径权限，使用账号密码去连接测试时会报连接超时的问题，命令行是正常的。

需要确认一下你连接的ip是否正确，workbench web版的连接是从server部署所在机器连接目标etcd节点，并不是浏览器所在机器去连接，如果是内网地址的话需要特别注意一下这一点

**Comment by tzfun** [comment]
duplicate #15
