### ISSUE TITLE
建议优化：1.数据显示乱码；2.展示数据可以格式化。

### ISSUE THREAD

**Issue by yujitao** [tzfun/etcd-workbench#32]

**Comment by tzfun** [comment]
1. 麻烦提供一下乱码截图，最好提供一下乱码内容，如果内容本身无法被解析为utf8字符的话是无法正确显示的
2. 格式化功能暂时没有计划做，它的成本比较高，你可以提交pr来完成它或者提供可靠的工具插件

**Comment by yujitao** [comment]
我是连的k8s集群的etcd，就像这样
![image](https://github.com/user-attachments/assets/cfa32ea2-1ab7-4a91-8ad7-cec14c529bf4)

**Comment by tzfun** [comment]
这块内容包含了很多ASCII码，是无法被解析为可视文本的，或者使用了其他编码协议（例如Protobuf），配置内容本身就不是“文本”，你可以用其他工具或者写代码读取内容到本地验证一下

**Comment by yujitao** [comment]
> 这块内容包含了很多ASCII码，是无法被解析为可视文本的，或者使用了其他编码协议（例如Protobuf），配置内容本身就不是“文本”，你可以用其他工具或者写代码读取内容到本地验证一下

好吧

**Comment by andyz168** [comment]
> 这块内容包含了很多ASCII码，是无法被解析为可视文本的，或者使用了其他编码协议（例如Protobuf），配置内容本身就不是“文本”，你可以用其他工具或者写代码读取内容到本地验证一下

这种乱码的文本，有什么思路能可视化看起来，不那么费劲

**Comment by tzfun** [comment]
> 这种乱码的文本，有什么思路能可视化看起来，不那么费劲

有一个办法倒是可以解决protobuf的展示问题，首先protobuf反序列化出的二进制内容必须要有对应的pb定义文件才能正确解析，用户查看文件时需导入protobuf定义文件，然后客户端实时生成解析脚本将内容转换为json展示，但有以下几个问题：

1. 实现难度较高，无论是生成js 还是python脚本，亦或是shell脚本都依赖本地额外的开发环境
2. protobuf定义文件获取代价较大，例如k8s中pod数据的protobuf定义文件多样且不易获取，寻常用户使用etcd客户端还要去找对应的pb源文件是比较繁琐的
3. 引入后App理解成本增加，查看这类pb内容的操作会变得繁琐
4. 这种解决方式只是解决protobuf序列化面临的问题，但不能解决其他序列化内容可视化问题

综合来看这个方法虽然能勉强解决但”性价比“不高，如果你有更好的解决方案欢迎提交PR。

**Comment by tzfun** [comment]
@andyz168 @yujitao 
已发布 [1.1.1](https://github.com/tzfun/etcd-workbench/releases/tag/App-1.1.1) 版本支持格式化kubernetes中的protobuf内容
