### ISSUE TITLE
key内容支持一键格式化

### ISSUE THREAD

**Issue by AGou-ops** [tzfun/etcd-workbench#37]
![CleanShot 2024-09-11 at 15 42 02@2x](https://github.com/user-attachments/assets/bf688914-915c-4463-8791-c7b0c93233b9)

这样看起来不是很方便，得复制到别的地方格式化一下. 🤣

**Comment by tzfun** [comment]
查看的内容是按原本格式展示的，后续可以考虑加一个格式化功能

**Comment by tzfun** [comment]
已发布 [App-1.0.3](https://github.com/tzfun/etcd-workbench/releases/tag/App-1.0.3) 支持格式化，目前支持有json、xml、html、sql、yaml的格式化，点击右下角格式选择 > Format可一键格式化，或使用快捷键 Ctrl + Alt + L

注：Web版暂不支持
