### ISSUE TITLE
这个工具怎么连接到k8s单机集群

### ISSUE THREAD

**Issue by andyz168** [tzfun/etcd-workbench#41]
有没有说明文档 k8s要配置啥，workbench要配置啥

**Comment by tzfun** [comment]
> 有没有说明文档 k8s要配置啥，workbench要配置啥

这个工具只是etcd的客户端连接工具，和k8s没有强相关，只要是使用了etcd的集群都可以使用Workbench连接，就和你平时使用etcdctl命令行一样。

无论k8s集群是内置的还是外置的etcd，有它的ip 端口 账号密码以及ssl证书（如果配置了的话）就可以直接使用Workbench连接。另外如果你的连接主机与etcd部署环境网络不通，可以使用SSH Tunnel（本工具中有配置）连接到一个与etcd可以连接的主机进行消息转发。

**Comment by andyz168** [comment]
这个问题解决了，思路是先将etcd 通过service暴露出来，具体可以参考这个文章https://cloud.tencent.com/developer/article/2064834
现在有个问题，是解码之后看起来还是比较乱
![image](https://github.com/user-attachments/assets/c5628883-54b9-4a7f-af77-39668dfa5aaa)

**Comment by andyz168** [comment]
> > 有没有说明文档 k8s要配置啥，workbench要配置啥
> 
> 这个工具只是etcd的客户端连接工具，和k8s没有强相关，只要是使用了etcd的集群都可以使用Workbench连接，就和你平时使用etcdctl命令行一样。
> 
> 无论k8s集群是内置的还是外置的etcd，有它的ip 端口 账号密码以及ssl证书（如果配置了的话）就可以直接使用Workbench连接。另外如果你的连接主机与etcd部署环境网络不通，可以使用SSH Tunnel（本工具中有配置）连接到一个与etcd可以连接的主机进行消息转发。

这个问题解决了，思路是先将etcd 通过service暴露出来，具体可以参考这个文章https://cloud.tencent.com/developer/article/2064834
现在有个问题，是解码之后看起来还是比较乱
![image](https://github.com/user-attachments/assets/c5628883-54b9-4a7f-af77-39668dfa5aaa)

**Comment by tzfun** [comment]
> 现在有个问题，是解码之后看起来还是比较乱

可以看一下这个issue https://github.com/tzfun/etcd-workbench/issues/32#issuecomment-2303859025

k8s内部分数据是用的protobuf，它本身就不是可阅读的文本格式，所以你用text去解析它会出现乱码，对于这种非可视化二进制内容或加密内容无法用text查看的

**Comment by tzfun** [comment]
@andyz168 
已发布 [1.1.1](https://github.com/tzfun/etcd-workbench/releases/tag/App-1.1.1) 版本支持格式化kubernetes中的protobuf内容
