### ISSUE TITLE
[建议] 左侧的tree增加关键字搜索

### ISSUE THREAD

**Issue by andyz168** [tzfun/etcd-workbench#42]
![image](https://github.com/user-attachments/assets/8515b879-5fe0-47db-8042-ef59c2299453)
比如我搜索higress，会搜索所有higress节点，并展开

**Comment by tzfun** [comment]
Web版本有搜索功能，App在下一个版本发布时随之更新

**Comment by tzfun** [comment]
已发布 [App-1.0.3](https://github.com/tzfun/etcd-workbench/releases/tag/App-1.0.3) 支持此功能
