### ISSUE TITLE
网页和PC版本，能自动识别格式，用对应的格式显示么？

### ISSUE THREAD

**Issue by zhoukai83** [tzfun/etcd-workbench#44]
![image](https://github.com/user-attachments/assets/ffa861d7-b5c5-46c9-acf0-2873b4752a2c)

如果不行的话，那假如我设置了一个键值的格式为yaml, 下次能默认用上次设置的格式么？
现在这样每次都得手动更改格式，很不方便

**Comment by tzfun** [comment]
是有自动识别格式的，按照以下优先级识别：
1. key名格式解析，例如Yaml的文件名通常为 `*.yml` 、`*.yaml`
2. value首行解析，例如Json的文件首行以`[` 、`{` 开始，Yaml文件以 `---`、`xxx: xxx`开始等

主要还是按照key名格式来识别更为准确，value首行解析准确性不高。

但实际使用情况下来大多数key并不会特意给键名加上后缀，所以导致了你出现的这个问题，不过你提醒了我，我觉得可以再加一条规则，在App中维护一个有限长度的队列，用于记忆**已修改过**的key格式，当某个key在打开后修改过格式就将此行为记下来，下次打开相同key时从队列中读取格式。

**Comment by tzfun** [comment]
此问题移步到issue： #49
