### ISSUE TITLE
buttons overlap when zooming 

### ISSUE THREAD

**Issue by ArthurBussiere** [tzfun/etcd-workbench#6]
buttons are overlap when zoom or reduce the size of the windows.
![Enregistrement-2024-04-13-192034](https://github.com/tzfun/etcd-workbench/assets/43986489/cf1c9022-cd7d-492b-ae93-9efb40f3148b)

Thank you !

**Comment by tzfun** [comment]
I will fix it soon, thanks for your support.

**Comment by tzfun** [comment]
I tried to optimize it in version `1.1.2`, but because my equipment is limited, I cannot guarantee that it will display well under your media. I have tried my best to optimize it. If there are still problems, please reopen this issue.
