### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by huai168an** [tzfun/etcd-workbench#7]
1. 界面上没有workbench的版本信息，现在不知道是不是最新版，建议在右下角或者其他地方加上
2. 在删除key后，如果不刷新或退出，当前key的内容还是一直显示
3. 新建key有点麻烦，必须有value才能建，能不能像etcdkeeper那样，可以建文件夹和空的key
4. 退出账号后在登陆进行，在连接退出前的etcd的时候出现“Session name exists: youle_etcd”，必须刷新才能在次连接，这是bug？
5. docker镜像能否支持下arm64的，每次都要自己打包镜像的，版本更新快的话，还是有点不方便

etcd使用版本：3.5.13

非常感谢作者，提供很好的软件让我们使用，辛苦了！

**Comment by tzfun** [comment]
1. 很好的建议，计划在下个版本加上
2. 这个是一个缓存问题，下个版本修复
3. 目前可能不太好支持创建空文件夹，只有空文件夹对table view显示不太友好，空的key可以支持
4. 这也是一个缓存问题，之前没测试到，下个版本修复 👍 
5. arm64的镜像之前还没有搞过，正好学习一下，我们可以加微信沟通：beifeng-tz

项目来源于我平时的开发工作，或许在其他应用场景还有很多缺陷，但我会持续更新维护，感谢你对工具的支持 😊

**Comment by tzfun** [comment]
以上建议和bug已 1.1.3 版本更新，此后版本docker镜像也开始arm64架构
<img width="733" alt="image" src="https://github.com/tzfun/etcd-workbench/assets/34815354/1b72cbc7-d463-4ece-bff2-56ad683cc59a">
